### ISSUE TITLE
Lizenz

### ISSUE THREAD

**Issue by SimplicityApks** [RWTH-OS/gi4_uebung01#4]
Die Creative Commons Lizenz sollte laut des eigenen [FAQs](https://creativecommons.org/faq) nicht für SourceCode verwendet werden, da sie nicht mit anderen Lizenzen wie der GPL kompatibel ist. Dadurch kann Code der mit der Übung abgegeben wird nie in anderen Projekten (mit anderer Lizenz) verwendet werden. 

Mir ist bewusst, dass es ohnehin wahrscheinlich wenig Wiederverwendungswert in dem Übungscode gibt aber es geht mir hier auch ums Prinzip und vor allem um die Vorbildfunktion. Denn so bringt man evtl noch mehr Leute dazu Code (weiter) unter der CC zu veröffentlichen (was die ohnehin schon schwierige Lizenzsituation auch noch verkompliziert).

Ich würde stattdessen empfehlen die Übungen unter die [GPL](http://www.gnu.org/licenses/gpl.html) oder die etwas tolerantere [MPL](https://www.mozilla.org/en-US/MPL/2.0/) zu stellen, da dann hier abgegebener Code zumindest auch in OpenSource Projekten verwendet werden kann, durch das Copyleft aber keine Nachteile entstehen.

**Comment by stlankes** [comment]
Hm, stimmt. Die Lizenz habe ich eher für die Aufgabenstellung gewählt. Der Code sollte hierüber nicht lizenziert werden. Werde ich korrigieren.

**Comment by stlankes** [comment]
Ist es nun eindeutiger?

**Comment by SimplicityApks** [comment]
Ja, so ist es besser, vielen Dank!
